name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install bats-core and dependencies
        run: sudo apt-get update && sudo apt-get install -y bats ripgrep
      - name: Install tokei        run: |          TOKEI_VERSION="$(curl -s https://api.github.com/repos/XAMPPRocky/tokei/releases/latest | grep -oP '"tag_name": "v\K[0-9.]+'))"          curl -sSL "https://github.com/XAMPPRocky/tokei/releases/download/v${TOKEI_VERSION}/tokei-x86_64-unknown-linux-gnu" -o /usr/local/bin/tokei          sudo chmod +x /usr/local/bin/tokei
      - name: Make script executable
        run: chmod +x universal-toolkit.sh
      - name: Run tests
        run: bats tests
